# Configuração da exchange (carregada do .env)
exchange:
  apiKey: "${BINANCE_API_KEY}"
  secret: "${BINANCE_API_SECRET}"
  enableRateLimit: true
  testnet: true
  options:
    defaultType: "spot"
    adjustForTimeDifference: true
    createMarketBuyOrderRequiresPrice: false

# Configuração dos pares de trading
trading_pairs:
  # Bitcoin com Trend Following (Large Cap)
  - symbol: "BTC/USDT"
    strategy: "trend_following"
    strategy_params:
      ema_fast: 12
      ema_slow: 26
      volume_multiplier: 1.5
      atr_period: 14
      trend_strength_threshold: 0.001
    amount: 0.001

  # Ethereum com Mean Reversion (Large Cap)
  - symbol: "ETH/USDT"
    strategy: "mean_reversion"
    strategy_params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      volume_threshold: 1.2
    amount: 0.01

  # BNB com Breakout Trading (Mid Cap)
  - symbol: "BNB/USDT"
    strategy: "breakout"
    strategy_params:
      consolidation_period: 20
      min_consolidation_period: 10
      max_consolidation_range: 0.03
      breakout_threshold: 0.005
      volume_multiplier: 1.8
      stop_loss_distance: 0.02
    amount: 2

  # Solana com Momentum Volume (Mid Cap)
  - symbol: "SOL/USDT"
    strategy: "momentum_volume"
    strategy_params:
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      momentum_period: 10
      price_momentum_threshold: 0.02
      volume_period: 20
      volume_multiplier: 1.5
      rsi_momentum_threshold: 50
    amount: 1

  # Cardano com Breakout Trading (Mid Cap)
  - symbol: "ADA/USDT"
    strategy: "breakout"
    strategy_params:
      consolidation_period: 15
      min_consolidation_period: 8
      max_consolidation_range: 0.04
      breakout_threshold: 0.006
      volume_multiplier: 2.0
      stop_loss_distance: 0.025
    amount: 100

# Configurações de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "trading_bot.log"

# Configurações gerais
general:
  update_interval_seconds: 60
  show_summary_interval_minutes: 5
  max_concurrent_trades: 3

# Configurações de monitoramento de mercado - TEMPO REAL
market_monitoring:
  websocket_enabled: true    # ✅ HABILITADO para tempo real
  websocket_ping_interval: 20  # ping a cada 20s
  websocket_reconnect_delay: 5  # delay de reconexão
  rest_fallback_interval: 5  # fallback REST apenas se WS falhar
  database_cleanup_days: 7   # manter dados por 7 dias
  order_book_depth: 20       # mais níveis para melhor análise
  price_tick_history_limit: 2000  # histórico maior para indicadores
  real_time_analysis: true   # análise em tempo real nos callbacks
  tick_analysis_threshold: 0.001  # 0.1% mudança para trigger análise

# Gestão de risco e capital - CONSERVADOR
risk_management:
  # Perfil de risco: conservative, moderate, aggressive
  risk_profile: "conservative"
  
  # Tamanho de posição: fixed_amount, percentage_balance, risk_based, kelly_criterion
  position_sizing:
    type: "risk_based"
    fixed_amount: 50.0        # Valor fixo conservador
    balance_percentage: 0.03  # Apenas 3% do balanço por posição
  
  # Limites de risco - MUITO CONSERVADORES
  limits:
    max_risk_per_trade: 0.005   # 0.5% do capital por trade
    max_portfolio_risk: 0.02    # 2% do capital total em risco
    max_concurrent_trades: 3
    max_daily_loss: 0.015       # 1.5% de perda máxima diária
  
  # Stop-loss e take-profit padrão
  stop_loss:
    default_percentage: 0.015   # 1.5% stop-loss
    trailing_enabled: true
    trailing_distance: 0.01     # 1% de distância
    trailing_step: 0.003        # 0.3% step para ajuste
  
  take_profit:
    default_percentage: 0.03    # 3% take-profit (R:R 1:2)
    
  # Verificações de segurança
  safety_checks:
    verify_balance_before_trade: true
    minimum_balance_reserve: 0.15  # 15% de reserva de saldo
